# Generated by Django 5.2.4 on 2026-05-21 09:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeprofile',
            name='emp_id',
            field=models.CharField(blank=True, max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='Employee ID must be exactly 4 digits.', regex='^\\d{4}$')]),
        ),
    ]
