# Generated by Django 6.0.4 on 2026-04-29 07:45

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=255)),
                ('mac_address', models.CharField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('country', models.CharField(default='India', max_length=255)),
                ('comments', models.TextField(blank=True)),
                ('follow_up_time', models.DateTimeField(blank=True, null=True)),
                ('payment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('action', models.CharField(blank=True, choices=[('call', 'Call'), ('follow_up', 'Follow Up'), ('closed', 'Closed')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
