# Generated by Django 5.2.4 on 2026-05-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mac_address',
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
